import type { Metadata } from "next";
import { Oxanium } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Oxanium({
  subsets : ['latin'] ,
  weight :['500' , '600' ,'700' ,'800']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="" >
        <div className="containerVectors">

     
        <div className={`sm:px-24 px-6 ${font.className} py-4`}>
        <Header/>
        {children}
     
        </div>
        <Footer />
        </div>
        </body>
    </html>
  );
}
